import 'package:firebase_auth/firebase_auth.dart';
import 'package:get/get.dart';

/// Admin status is derived ONLY from the Firebase Auth ID token's custom
/// claims (`admin: true`), never from a Firestore field — a claim can't be
/// forged by a client the way a Firestore document can.
///
/// Also owns the TOTP second-factor (2FA) flow: enrollment for the current
/// user, and the sign-in challenge when an already-enrolled account signs in.
class AuthService extends GetxService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  final Rxn<User> firebaseUser = Rxn<User>();
  final RxBool isAdmin = false.obs;
  final RxBool ready = false.obs;

  /// Set while a sign-in attempt is paused waiting for a TOTP code — the
  /// login screen watches this to switch from the password form to the
  /// 2FA code form.
  final Rxn<MultiFactorResolver> mfaResolver = Rxn<MultiFactorResolver>();

  User? get currentUser => _auth.currentUser;

  Future<AuthService> init() async {
    _auth.authStateChanges().listen(_onAuthChanged);
    await _onAuthChanged(_auth.currentUser);
    return this;
  }

  Future<void> _onAuthChanged(User? user) async {
    firebaseUser.value = user;
    if (user == null) {
      isAdmin.value = false;
      ready.value = true;
      return;
    }
    await refreshAdminClaim();
    ready.value = true;
  }

  /// Forces an ID token refresh so a claim granted moments ago (e.g. right
  /// after bootstrap) is picked up instead of a stale cached token.
  Future<void> refreshAdminClaim() async {
    final user = _auth.currentUser;
    if (user == null) {
      isAdmin.value = false;
      return;
    }
    final result = await user.getIdTokenResult(true);
    isAdmin.value = result.claims?['admin'] == true;
  }

  /// Returns a user-facing error message on failure, or null on success —
  /// EXCEPT when a second factor is required, in which case this also
  /// returns null but sets [mfaResolver]; callers must check
  /// `mfaResolver.value != null` after a null result to tell "signed in"
  /// apart from "waiting for a 2FA code".
  Future<String?> signIn(String email, String password) async {
    try {
      await _auth.signInWithEmailAndPassword(
        email: email.trim(),
        password: password,
      );
      return _afterFirstFactorSignIn();
    } on FirebaseAuthMultiFactorException catch (e) {
      mfaResolver.value = e.resolver;
      return null;
    } on FirebaseAuthException catch (e) {
      return _mapAuthError(e);
    }
  }

  /// Completes a sign-in that was paused by [signIn] for a TOTP challenge.
  Future<String?> submitMfaCode(String code) async {
    final resolver = mfaResolver.value;
    if (resolver == null) {
      return 'Beklenmeyen bir durum oluştu, lütfen tekrar giriş yapmayı deneyin.';
    }
    final totpHint = resolver.hints
        .whereType<TotpMultiFactorInfo>()
        .firstOrNull;
    if (totpHint == null) {
      return 'Bu hesap için desteklenen bir 2FA yöntemi bulunamadı.';
    }
    try {
      final assertion = await TotpMultiFactorGenerator.getAssertionForSignIn(
        totpHint.uid,
        code.trim(),
      );
      await resolver.resolveSignIn(assertion);
      mfaResolver.value = null;
      return _afterFirstFactorSignIn();
    } on FirebaseAuthException catch (e) {
      return _mapAuthError(e);
    }
  }

  /// Abandons a pending 2FA challenge (e.g. user clicks "back" on the login screen).
  void cancelMfaChallenge() {
    mfaResolver.value = null;
  }

  Future<String?> _afterFirstFactorSignIn() async {
    await refreshAdminClaim();
    if (!isAdmin.value) {
      await _auth.signOut();
      return 'Bu hesabın admin yetkisi yok.';
    }
    return null;
  }

  // ---------------------------------------------------------------------
  // TOTP enrollment for the CURRENTLY signed-in admin (their own account).
  // ---------------------------------------------------------------------

  Future<bool> hasTotpEnrolled() async {
    final user = _auth.currentUser;
    if (user == null) return false;
    final factors = await user.multiFactor.getEnrolledFactors();
    return factors.whereType<TotpMultiFactorInfo>().isNotEmpty;
  }

  /// Starts enrollment: generates a fresh TOTP secret tied to a new
  /// multi-factor session for the current user.
  Future<TotpSecret> startTotpEnrollment() async {
    final user = _auth.currentUser;
    if (user == null) throw StateError('Oturum açık değil.');
    final session = await user.multiFactor.getSession();
    return TotpMultiFactorGenerator.generateSecret(session);
  }

  /// Confirms enrollment with the first code generated by the admin's
  /// authenticator app for [secret].
  Future<void> confirmTotpEnrollment(TotpSecret secret, String code) async {
    final user = _auth.currentUser;
    if (user == null) throw StateError('Oturum açık değil.');
    final assertion = await TotpMultiFactorGenerator.getAssertionForEnrollment(
      secret,
      code.trim(),
    );
    await user.multiFactor.enroll(assertion, displayName: 'Authenticator App');
  }

  Future<void> unenrollTotp() async {
    final user = _auth.currentUser;
    if (user == null) return;
    final factors = await user.multiFactor.getEnrolledFactors();
    final totp = factors.whereType<TotpMultiFactorInfo>().firstOrNull;
    if (totp == null) return;
    await user.multiFactor.unenroll(multiFactorInfo: totp);
  }

  Future<void> signOut() => _auth.signOut();

  String _mapAuthError(FirebaseAuthException e) {
    switch (e.code) {
      case 'user-not-found':
      case 'wrong-password':
      case 'invalid-credential':
        return 'E-posta veya şifre hatalı.';
      case 'user-disabled':
        return 'Bu hesap devre dışı bırakılmış.';
      case 'too-many-requests':
        return 'Çok fazla deneme yapıldı, lütfen daha sonra tekrar deneyin.';
      case 'invalid-verification-code':
        return 'Doğrulama kodu hatalı.';
      default:
        return 'Giriş yapılamadı (${e.code}).';
    }
  }
}
